-- Account: id, code, name, type, balance, version (optimistic lock)
CREATE TABLE account (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(50)  NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    balance    DECIMAL(19, 4) NOT NULL DEFAULT 0,
    version    BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_account_code ON account(code);

-- Ledger transaction (avoid reserved word 'transaction')
CREATE TABLE ledger_transaction (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(500) NOT NULL,
    timestamp    TIMESTAMP(6) NOT NULL,
    reference_id VARCHAR(100)
);

CREATE INDEX idx_ledger_transaction_reference_id ON ledger_transaction(reference_id);

-- Entry: links transaction to account with amount and type
CREATE TABLE entry (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    account_id    BIGINT NOT NULL,
    amount        DECIMAL(19, 4) NOT NULL,
    type          VARCHAR(10) NOT NULL,
    CONSTRAINT fk_entry_transaction FOREIGN KEY (transaction_id) REFERENCES ledger_transaction(id),
    CONSTRAINT fk_entry_account    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE INDEX idx_entry_transaction_id ON entry(transaction_id);
CREATE INDEX idx_entry_account_id ON entry(account_id);
