-- Budgeting: limites de gastos por categoria (valor absoluto ou percentual da renda)
CREATE TABLE budget_limit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   VARCHAR(100) NOT NULL,
    limit_type VARCHAR(20)  NOT NULL,
    limit_value DECIMAL(19, 4) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_budget_limit_category ON budget_limit(category);

-- Metas de investimento: taxa de retorno esperada e aportes mensais planejados
CREATE TABLE investment_goal (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    expected_return_rate  DECIMAL(10, 4) NOT NULL,
    monthly_contribution  DECIMAL(19, 4) NOT NULL,
    target_amount         DECIMAL(19, 4),
    created_at            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Parâmetros econômicos: expectativa Selic e IPCA para simulações
CREATE TABLE economic_parameters (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selic_rate DECIMAL(10, 4) NOT NULL,
    ipca_rate  DECIMAL(10, 4) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
